# Generated by Django 5.2.3 on 2025-07-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseexercise',
            name='equipment',
        ),
    ]
