# Generated by Django 5.2.4 on 2025-09-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='base_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='logger.baseexercise'),
        ),
    ]
