# Generated by Django 5.2.3 on 2025-07-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_remove_baseexercise_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
    ]
