# Generated by Django 5.2.1 on 2025-05-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_calorieentry_remove_workout_date_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieentry',
            name='daily_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.dailylog'),
        ),
        migrations.AddField(
            model_name='workout',
            name='daily_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.dailylog'),
        ),
    ]
