# Generated by Django 5.2.1 on 2025-05-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_baseexercise_exercise_form_note_exercise_grip_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(to='logger.equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(to='logger.musclegroup'),
        ),
    ]
