# Generated by Django 5.2.1 on 2025-06-02 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_workout_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorieentry',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='baseexercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='form_note',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='grip_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_single_arm',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='parent',
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='daily_logs', to='logger.calorieentry'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='daily_logs', to='logger.workout'),
        ),
        migrations.CreateModel(
            name='SubMuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='logger.musclegroup')),
            ],
        ),
    ]
