# Generated by Django 5.2.1 on 2025-06-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_rename_food_name_calorieentry_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='workouts',
        ),
    ]
