# Generated by Django 5.2.1 on 2025-06-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_remove_dailylog_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='daily_logs', to='logger.workout'),
        ),
    ]
